### PR TITLE
WIP: adding support for vbox, crude way right now

### PR DESCRIPTION
**Pull request by saneax**
This enables the allinone example to run on virtualbox, better way would be to segregate the division though an yaml file.

### CODE REVIEW

**Comment by cmurphy** [comment]
The puppetlabs/ubuntu-14.04-64-puppet and puppetlabs/centos-7.0-64-puppet boxes are already compatible with virtualbox, so I don't think you need to change the box. All that should be needed is an additional section for virtualbox that sets the memory and cpus in the virtualbox-compatible way. You shouldn't need two Vagrantfiles.

I would rather not change the boxes to be ubuntu instead of centos. Instead I'd rather have a way for the user to choose. There is already sort of a way to generate an ubuntu vagrant environment in the tests/ directory but I haven't explored it and I'm not sure how user friendly it is.

**Comment by saneax** [comment]
Hi Colleen,

(inline)

On Mon, Apr 27, 2015 at 10:34 PM, Colleen Murphy <notifications@github.com>
wrote:

> The puppetlabs/ubuntu-14.04-64-puppet and puppetlabs/centos-7.0-64-puppet
> boxes are already compatible with virtualbox, so I don't think you need to
> change the box. All that should be needed is an additional section for
> virtualbox that sets the memory and cpus in the virtualbox-compatible way.
> You shouldn't need two Vagrantfiles.
>

I get the above. I am working on segregating the variables inside the
Vagrantfile. So all moving variables can be taken from a yaml file ie. box
type, vm provider, the network, cpu, mem.

I am not sure, if it makes sense to do all that. I couldnt find an easy way
to get things up for allinone without the changes.

> I would rather not change the boxes to be ubuntu instead of centos.
> Instead I'd rather have a way for the user to choose. There is already sort
> of a way to generate an ubuntu vagrant environment in the tests/ directory
> but I haven't explored it and I'm not sure how user friendly it is.
>

I will work on making it more friendly, Please suggest if you have anything
in mind.

regards
/sanjay

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppetlabs-openstack/pull/183#issuecomment-96741841>
> .
>



-- 
Sanjay Upadhyay
http://saneax.blogspot.com

**Comment by cmurphy** [comment]
> I am not sure, if it makes sense to do all that. I couldnt find an easy way to get things up for allinone without the changes.

I think it should already just work, except that the memory and cpus won't be set, which should be fixed with just an additional stanza to set those, i.e. another section like https://github.com/puppetlabs/puppetlabs-openstack/blob/master/examples/allinone/Vagrantfile#L47-L51 but using the virtualbox provider instead.

> I will work on making it more friendly, Please suggest if you have anything in mind.

One idea could be to add parallel boxes for centos and ubuntu. For example, another section like https://github.com/puppetlabs/puppetlabs-openstack/blob/master/examples/allinone/Vagrantfile#L30-L52 but called allinone_ubuntu and specifying `allinone_ubuntu.vm.box = = "puppetlabs/ubuntu-14.04-64-puppet"`.

Another way could be generating them using templates, but I think that would end up adding clutter that could accidentally get committed.

Thanks for working on this, I'm happy to get better support for virtualbox in these examples.

**Comment by salmankh** [comment]
Can someone tell me how the review request is generated. I made the pull request couple of weeks ago but nobody reviews it, not sure where should I request for review?

**Comment by cmurphy** [comment]
Any update on this?

**Comment by saneax** [comment]
Hi Colleen

I have made some changes. Sorry this took a long time. 
the changes under 'examples/allinone/Vagrantfile' are redundant so they will go. 

what should be good to go ahead is in 
examples/make_ubuntu_allinone.sh
manifests/profile/mysql.pp (this was throwing error, so I commented out)
in tests/modules/plostest/data/scenarios/allinone.yaml we have added one more node parameter which is vm_provider.

tests/modules/plostest/templates/Vagrantfile.erb (has the changes to take virtual box and vmware_fusion, we should be able to add more)

this is still WIP, I will update after cleaning up

**Comment by benh57** [comment]
FWIW i have been using these modules for over a year with Colleen's
suggested method (just adding provisioner blocks for virtualbox) and it
works fine,I just never submitted my changes upstream. ;)

**Comment by saneax** [comment]
Another thing on the same topic, does it make sense to run puppet apply
(decentralized puppet code)

we mount the puppet code on each VM via 'puppet.vm.synced_folder "../../",
"/openstack"'
and run puppet apply on that. I am still beginning and am not sure if this
will work at all.

My laptop ram is limited and I want to have a functional minimal Openstack
setup, and just want to omit any VM which can be omitted.

Any pointers would help.

regards
/sanjay

On Fri, Aug 28, 2015 at 11:06 PM, Sanjay Upadhyay saneax@gmail.com wrote:

> On Fri, Aug 28, 2015 at 9:55 PM, benh57 notifications@github.com wrote:
> 
> > FWIW i have been using these modules for over a year with Colleen's
> > suggested method (just adding provisioner blocks for virtualbox) and it
> > works fine,I just never submitted my changes upstream. ;)
> > 
> > so this is not required?
> 
> if thats the case, I can as well make it work just for me and move on :)
> 
> regards
> /sanjay
> 
> > On Fri, Aug 28, 2015 at 7:30 AM, Sanjay Upadhyay <
> > notifications@github.com>
> > wrote:
> > 
> > > Hi Colleen
> > > 
> > > I have made some changes. Sorry this took a long time.
> > > the changes under 'examples/allinone/Vagrantfile' are redundant so they
> > > will go.
> > > 
> > > what should be good to go ahead is in
> > > examples/make_ubuntu_allinone.sh
> > > manifests/profile/mysql.pp (this was throwing error, so I commented out)
> > > in tests/modules/plostest/data/scenarios/allinone.yaml we have added one
> > > more node parameter which is vm_provider.
> > > 
> > > tests/modules/plostest/templates/Vagrantfile.erb (has the changes to
> > > take
> > > virtual box and vmware_fusion, we should be able to add more)
> > > 
> > > this is still WIP, I will update after cleaning up
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/puppetlabs/puppetlabs-openstack/pull/183#issuecomment-135788776
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/puppetlabs/puppetlabs-openstack/pull/183#issuecomment-135824687
> > .
> 
> ## 
> 
> Sanjay Upadhyay
> http://saneax.blogspot.com

## 

Sanjay Upadhyay
http://saneax.blogspot.com

**Pull request closed without merging**
