### PR TITLE
Allow user to set non-default username/password pair for database connectors

### PR DESCRIPTION
**Pull request by guessi**

### CODE REVIEW

**Comment by cmurphy** [comment]
In this case I think it would be cleaner to use the pick() function to set the value instead of wrapping each connection string in the if/else. For example, in manifests/init.pp

```
mysql_user_keystone => pick(hiera(openstack::mysql::keystone::user, undef), 'keystone')
mysql_pass_keystone => pick(hiera(openstack::mysql::keystone::pass, undef), hiera(openstack::mysql::service_password))
...
mysql_user_keystone => pick($mysql_user_keystone, 'keystone')
mysql_pass_keystone => pick($mysql_pass_keystone, $mysql_service_password)
```

Then using the values would just be
```
$user_keystone = $::openstack::config::mysql_user_keystone
$pass_keystone = $::openstack::config::mysql_pass_keystone
$keystone   = "mysql://${user_keystone}:${pass_keystone}@${management_address}/keystone"
```

What do you think?

**Comment by guessi** [comment]
umm... it have been reset to `undef` in `config.pp` already, do we need double protection for these values?

and more, if we do a `undef` protection for this case, should we do the same trick for the other parameters in `init.pp`, e.g. `nova_password`,

or maybe we should create another pull request to do these jobs.

what's your opinion for that?

**Comment by cmurphy** [comment]
The undef I put in the hiera function is only there because otherwise hiera would fail if it wasn't there. Then the pick() function can set the correct value, e.g. 'keystone' or the keystone password, if the hiera function didn't find the value. My suggestion is not double protection, it's to make sure the value is set prior to being used in openstack::resources::connectors. Then we no longer need the if/else statements to check whether it is set to undef in openstack::resources::connectors, we can just use it normally because we know it was set to the correct value in init.pp.

**Comment by guessi** [comment]
got you piont! changes committed.

**Comment by cmurphy** [comment]
I found an issue with the mongo pr that I think is present here as well. The connection string is changed, but the database is still set to use the old password. To fix this, I think we need to add 
```puppet
$user = getvar("::openstack::config::mysql_user_${title}")
$pass = getvar("::openstack::config::mysql_pass_${title}")
```
to openstack::resources::database and change the user and password parameters to use those values instead of $title and $::openstack::config::mysql_service_password.

**Comment by guessi** [comment]
thanks for pointing out the issue,
but I would leave `dbname` to be untouched, $title, in `openstack::resources::database`, since we don't have a customizable option for that.

**Pull request merged**
